version: "3"
services:

  fpsense_vpn_opt:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - fauxapi-secret=PFFApRKMIQWl0HV5HbDsvQKJ
      - fauxapi-key=JOTkJxThIEvjPfTdRxX0kDFzQtK7bOYCDpbCZfPjzsM6Y9ba5mfz6AuhTqsP
      - host-address=192.168.1.1
      - host-port=468
    volumes:
      - ".:/usr/src/app/"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000"