version: "3"
services:

  fpsense_vpn_opt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pfsense-VPN-optimizer
    environment:
      - fauxapi-secret=[CHANGE]
      - fauxapi-key=[CHANGE]
      - host-address=[CHANGE]
      - host-port=[CHANGE]
    volumes:
      - ".:/usr/src/app/"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000"
