version: "3"
services:

  fpsense_vpn_opt:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FAUXAPI_SECRET=testsecretthatisatleast40characterslongbutlessthan128
      - FAUXAPI_KEY=testkeythatisatleast12characterslonglt4t
      - HOST_ADDRESS=192.168.1.1
      - HOST_PORT=468
    volumes:
      - ".:/usr/src/app/"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000"