version: "3"
services:

  fpsense_vpn_opt:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FAUXAPI_SECRET=[CHANGE]
      - FAUXAPI_KEY=[CHANGE]
      - HOST_ADDRESS=[CHANGE]
      - HOST_PORT=[CHANGE]
    volumes:
      - ".:/usr/src/app/"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5000"